### PR TITLE
Try running advanced example

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
I still can't wrap my head around how the examples work, as the simple example has no `setup` chunk yet shows everything 🤔

### CODE REVIEW

**Comment by itsdfish** [comment]
@DominiqueMakowski, I'm not sure how it works. I thought it had a setup block, but you are right. It does not. One possibility is that the @setup block creates a global scope across the different files. So maybe using a single @setup block in the first rendered page is sufficient. I don't think that would be a good design feature because it could create naming conflicts. 

By the way, for your more advanced examples which take a long time to run, can you use ```julia ``` blocks instead of @example? When the code runs quickly, I like @example because it serves as a visual test of the code, but unfortunately some Turing models are painfully slow.

**Comment by DominiqueMakowski** [comment]
I changed them as the julia blocks were not showing on the page. Should I re-reverse?

**Comment by itsdfish** [comment]
Yeah. I think it would work better to change back to the julia code block for these long running examples. It won't show the output, but it will show the code. [Here](https://raw.githubusercontent.com/itsdfish/SequentialSamplingModels.jl/master/docs/src/turing_advanced.md) is a working example. 

One of the problems with the long run times is that it makes debugging the docs painfully slow. I think the best way to balance tradeoffs between convenience and development time is to use standard julia blocks for the long running examples.

**Comment by itsdfish** [comment]
@DominiqueMakowski, thanks for the improvements and updates. Is this ready to be merged?

**Comment by DominiqueMakowski** [comment]
Yes i think so

**Pull request merged**
